import { IMAGE_FIELDS, LINK_FIELDS } from "./image";

/**
 * One fragment per Layout (Block Type). Type names are generated by WPGraphQL for ACF:
 * {FieldGroup}{Field}{Layout}Layout → PageBuilder + Blocks + Hero + Layout.
 * Adding a Block Type: add a Layout in SCF (acf-json/group_page_builder.json), a fragment here,
 * a case in adapter.ts, and a Block Component.
 */
export const HERO = /* GraphQL */ `
  fragment Hero on PageBuilderBlocksHeroLayout {
    heading
    subheading
    image { ...ImageFields }
    cta { ...LinkFields }
  }
`;

export const RICH_TEXT = /* GraphQL */ `
  fragment RichText on PageBuilderBlocksRichTextLayout { content }
`;

export const FEATURE_GRID = /* GraphQL */ `
  fragment FeatureGrid on PageBuilderBlocksFeatureGridLayout {
    heading
    features { title text image { ...ImageFields } }
  }
`;

export const MEDIA_TEXT = /* GraphQL */ `
  fragment MediaText on PageBuilderBlocksMediaTextLayout {
    image { ...ImageFields }
    content
    imagePosition
  }
`;

export const CTA_BANNER = /* GraphQL */ `
  fragment CtaBanner on PageBuilderBlocksCtaBannerLayout {
    heading
    text
    cta { ...LinkFields }
  }
`;

export const PAGE_BUILDER = /* GraphQL */ `
  fragment PageBuilderFields on Page {
    pageBuilder {
      blocks {
        __typename
        ...Hero
        ...RichText
        ...FeatureGrid
        ...MediaText
        ...CtaBanner
      }
    }
  }
  ${HERO}
  ${RICH_TEXT}
  ${FEATURE_GRID}
  ${MEDIA_TEXT}
  ${CTA_BANNER}
  ${IMAGE_FIELDS}
  ${LINK_FIELDS}
`;
