<?php
/**
 * Demo content. Run via `ddev wp eval-file seed.php` (setup.sh does this).
 * Idempotent: re-running updates the same Pages, images, menu and settings.
 *
 * Writing Page Builder data in code: update_field() with the Flexible Content field
 * takes an array of rows, and each row names its Layout in `acf_fc_layout`.
 */

require_once ABSPATH . 'wp-admin/includes/media.php';
require_once ABSPATH . 'wp-admin/includes/file.php';
require_once ABSPATH . 'wp-admin/includes/image.php';

/**
 * Import brand artwork from ./assets once; reuse it on later runs.
 * The artwork is generated by web/scripts/generate-seed-art.mjs.
 */
function seed_image(string $file, string $alt): int {
	$existing = get_posts(['post_type' => 'attachment', 'meta_key' => '_seed_key', 'meta_value' => $file, 'fields' => 'ids', 'numberposts' => 1]);
	if ($existing) {
		return $existing[0];
	}
	// media_handle_sideload() moves the file it's given, so hand it a temporary copy.
	$tmp = wp_tempnam($file);
	copy(__DIR__ . "/assets/{$file}", $tmp);
	$id = media_handle_sideload(['name' => $file, 'tmp_name' => $tmp], 0);
	if (is_wp_error($id)) {
		WP_CLI::error("Image {$file}: " . $id->get_error_message());
	}
	update_post_meta($id, '_seed_key', $file);
	update_post_meta($id, '_wp_attachment_image_alt', $alt);
	return $id;
}

/** Create or update a published Page by slug. */
function seed_page(string $slug, string $title, string $excerpt, int $menu_order): int {
	$page = get_page_by_path($slug, OBJECT, 'page');
	$id = wp_insert_post([
		'ID'           => $page->ID ?? 0,
		'post_type'    => 'page',
		'post_status'  => 'publish',
		'post_name'    => $slug,
		'post_title'   => $title,
		'post_excerpt' => $excerpt,
		'menu_order'   => $menu_order,
	], true);
	if (is_wp_error($id)) {
		WP_CLI::error($id->get_error_message());
	}
	return $id;
}

$link = fn(string $title, string $url, string $target = '') => ['title' => $title, 'url' => $url, 'target' => $target];

// Remove WordPress's sample content so it doesn't show up on the frontend.
if ($sample = get_page_by_path('sample-page', OBJECT, 'page')) {
	wp_delete_post($sample->ID, true);
}

$home  = seed_page('home', 'Home', 'Lumen is a digital studio designing and building fast, editable, headless websites.', 0);
$about = seed_page('about', 'About', 'A small studio with a big toolbox: strategy, design and headless engineering.', 1);

update_field('field_pb_blocks', [
	[
		'acf_fc_layout' => 'hero',
		'heading'       => 'Websites that move at the speed of your ideas',
		'subheading'    => 'Lumen is a digital studio designing and building headless websites: WordPress to edit, Next.js to deliver, and a design system that keeps every page on brand.',
		'image'         => seed_image('hero.jpg', 'A glowing violet orb over a soft gradient'),
		'cta'           => $link('Meet the studio', home_url('/about/')),
	],
	[
		'acf_fc_layout' => 'rich_text',
		'content'       => '<h2>Content first, by design</h2><p>We start with your content model, not a template. Every section of this page is a <strong>Block</strong> that editors add, remove and reorder in WordPress. Next.js turns each one into a fast, accessible component.</p><ul><li>Strategy and content modelling</li><li>Design systems built for editors</li><li>Headless WordPress and Next.js builds</li></ul>',
	],
	[
		'acf_fc_layout' => 'feature_grid',
		'heading'       => 'How we build',
		'features'      => [
			['title' => 'Editor freedom', 'text' => 'Any Block, in any order, on any Page. Your team ships new pages without a developer.', 'image' => seed_image('feature-flexible.jpg', 'Stacked glass cards')],
			['title' => 'Built on structure', 'text' => 'Every Block has typed fields, not free-form HTML, so the design holds up whatever the content.', 'image' => seed_image('feature-structured.jpg', 'A fading grid over a gradient')],
			['title' => 'Fast by default', 'text' => 'Pages are pre-rendered and refreshed the moment an editor clicks Update.', 'image' => seed_image('feature-fast.jpg', 'A lightning bolt outline')],
		],
	],
	[
		'acf_fc_layout'  => 'media_text',
		'image'          => seed_image('media-text.jpg', 'Concentric rings over a violet gradient'),
		'content'        => '<h2>Designed with your editors</h2><p>We run workshops with the people who will use the CMS every day, then shape the Blocks around their work. The result is a Page Builder that feels obvious, and pages that always look intentional.</p>',
		'image_position' => 'right',
	],
	[
		'acf_fc_layout' => 'cta_banner',
		'heading'       => 'See the Page Builder in action',
		'text'          => 'Reorder these Blocks in WordPress, click Update, and watch this page change.',
		'cta'           => $link('Open wp-admin', admin_url('post.php?post=' . $home . '&action=edit'), '_blank'),
	],
], $home);

update_field('field_pb_blocks', [
	[
		'acf_fc_layout'  => 'media_text',
		'image'          => seed_image('about.jpg', 'Flowing lines over a violet gradient'),
		'content'        => '<h2>A small studio with a big toolbox</h2><p>Lumen is a team of strategists, designers and engineers. We have spent a decade building content platforms, and we believe the best CMS is the one your editors never have to think about.</p><p>This Page uses a different set of Blocks in a different order: same Page Builder, different content.</p>',
		'image_position' => 'left',
	],
	[
		'acf_fc_layout' => 'cta_banner',
		'heading'       => 'Back to the start',
		'text'          => 'See every Block Type on the home page.',
		'cta'           => $link('Explore the home page', home_url('/')),
	],
], $about);

// Settings → General. WPGraphQL exposes these as generalSettings { title description }.
update_option('blogname', 'Lumen Studio');
update_option('blogdescription', 'Headless websites, beautifully built.');

// wp_insert_post() above stores a revision when a Page changes, but update_field() writes the Blocks to the
// Page, not the revision. Draft Preview (asPreview) serves the latest revision or autosave, so a stale one
// would preview without Blocks. Clear them: with none, preview falls back to the Page itself.
foreach ([$home, $about] as $page_id) {
	foreach (wp_get_post_revisions($page_id, ['fields' => 'ids', 'check_enabled' => false]) as $revision_id) {
		wp_delete_post_revision($revision_id);
	}
	if ($autosave = wp_get_post_autosave($page_id)) {
		wp_delete_post($autosave->ID, true);
	}
}

// Reading settings: use a static Page as the front page (Settings → Reading).
update_option('show_on_front', 'page');
update_option('page_on_front', $home);

// Primary Menu, assigned to the `primary` location registered in headless-config.php.
$menu = wp_get_nav_menu_object('Primary') ?: get_term(wp_create_nav_menu('Primary'), 'nav_menu');
foreach (wp_get_nav_menu_items($menu->term_id) ?: [] as $item) {
	wp_delete_post($item->ID, true);
}
foreach ([$home, $about] as $position => $page_id) {
	wp_update_nav_menu_item($menu->term_id, 0, [
		'menu-item-object-id' => $page_id,
		'menu-item-object'    => 'page',
		'menu-item-type'      => 'post_type',
		'menu-item-status'    => 'publish',
		'menu-item-position'  => $position + 1,
	]);
}
set_theme_mod('nav_menu_locations', array_merge(get_theme_mod('nav_menu_locations', []) ?: [], ['primary' => $menu->term_id]));

// Site Settings (Options Page). 'option' is ACF's post_id for options pages.
update_field('field_ss_logo', seed_image('logo.png', 'Lumen Studio'), 'option');
update_field('field_ss_tagline', 'A digital studio building fast, editable, headless websites.', 'option');
update_field('field_ss_footer_columns', [
	['heading' => 'Studio', 'links' => [['link' => $link('Home', home_url('/'))], ['link' => $link('About', home_url('/about/'))]]],
	['heading' => 'Resources', 'links' => [
		['link' => $link('WPGraphQL', 'https://www.wpgraphql.com', '_blank')],
		['link' => $link('Next.js', 'https://nextjs.org', '_blank')],
	]],
], 'option');
update_field('field_ss_social', [
	['platform' => 'instagram', 'url' => 'https://instagram.com/'],
	['platform' => 'linkedin', 'url' => 'https://linkedin.com/'],
	['platform' => 'x', 'url' => 'https://x.com/'],
], 'option');
update_field('field_ss_copyright', '© {year} Lumen Studio. A headless WordPress proof of concept.', 'option');

// update_field() from the CLI doesn't fire the editor save hooks, so tell Next.js directly.
// (No-op if Next.js isn't running.)
headless_revalidate(['page:/', 'page:/about', 'pages', 'globals']);

WP_CLI::success("Seeded Home (#{$home}), About (#{$about}), Primary Menu and Site Settings.");
